### ISSUE TITLE
Onnx model not found

### ISSUE THREAD

**Issue by ivanravinovitch** [chflame163/ComfyUI_CatVTON_Wrapper#26]
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\STABLEDIFFUSION\ComfyUI\ComfyUI\models\onnx\human-parts\deeplabv3p-resnet50-human.onnx failed:Load model C:\STABLEDIFFUSION\ComfyUI\ComfyUI\models\onnx\human-parts\deeplabv3p-resnet50-human.onnx failed. File doesn't exist

Couldn't find it anywhere

**Comment by chflame163** [comment]
Download from [Here](https://huggingface.co/Metal3d/deeplabv3p-resnet50-human/tree/main)
And you can generate a mask using any other node that can segment clothing
