### ISSUE TITLE
What is the difference between the Google Drive models and this?

### ISSUE THREAD

**Issue by EmmanuelMr18** [chflame163/ComfyUI_CatVTON_Wrapper#29]
I was checking if the models exists in hugging face (they are easier to download).
In this project, looks that we have almost all the models https://huggingface.co/zhengchong/CatVTON/tree/main.
The only thing that changes is that the models are not exactly the same size, so I'm wondering if they are the same, or the ones in that repository are the latest one.

**Comment by chflame163** [comment]
They are the same, but you need to download the ```stable-diffusion-inpainting``` and ```sd-vae-ft-mse``` models separately and put them together

**Comment by EmmanuelMr18** [comment]
Got it, that makes sense.
I have uploaded the models to hugging face too, it is easier to download them if you cannot use the UI or to download from an automated program.
https://huggingface.co/EmmanuelMr/ComfyUI_CatVTON_Wrapper/tree/main

**Comment by chflame163** [comment]
> I have uploaded the models to hugging face too, it is easier to download them if you cannot use the UI or to download from an automated program. https://huggingface.co/EmmanuelMr/ComfyUI_CatVTON_Wrapper/tree/main

Good job! Thanks.
