### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by jisdf** [chflame163/ComfyUI_CatVTON_Wrapper#3]
![image](https://github.com/user-attachments/assets/23eca7e4-33a1-47ce-9153-02fc17a5b217)

**Comment by chflame163** [comment]
It seems there is an error on loading model file, delete the  ```diffusion_python_model.safetensors```  in ```ComfyUI/models/CatVTON/stable-diffusion-inpainting/unet```  and manual download the [diffusion_pytorch_model.bin](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/unet/diffusion_pytorch_model.bin)  or [diffusion_pytorch_model.fp16.bin](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/unet/diffusion_pytorch_model.fp16.bin) to this directory and  rename it to ```diffusion_python_model.safetensors```.

**Comment by jisdf** [comment]
> It seems there is an error on loading model file, delete the `diffusion_python_model.safetensors` in `ComfyUI/models/CatVTON/stable-diffusion-inpainting/unet` and manual download the [diffusion_pytorch_model.bin](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/unet/diffusion_pytorch_model.bin) or [diffusion_pytorch_model.fp16.safetensors](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/unet/diffusion_pytorch_model.fp16.safetensors) to this directory and rename it to `diffusion_python_model.safetensors`.


Thanks for the help, it worked!

**Comment by kaiyes** [comment]
doesn't work anymore.

Tried installing fp16.safetensor file & rename it to diffusion_python_model.safetensors, didn't work
![image](https://github.com/user-attachments/assets/62f1eb81-544c-46ae-a238-81f742196775)

**Comment by chflame163** [comment]
> doesn't work anymore.
> 
> Tried installing fp16.safetensor file & rename it to diffusion_python_model.safetensors, didn't work !

It seems that model files is missing

**Comment by kaiyes** [comment]
> It seems there is an error on loading model file, delete the `diffusion_python_model.safetensors` in `ComfyUI/models/CatVTON/stable-diffusion-inpainting/unet` and manual download the [diffusion_pytorch_model.bin](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/unet/diffusion_pytorch_model.bin) or [diffusion_pytorch_model.fp16.safetensors](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/unet/diffusion_pytorch_model.fp16.safetensors) to this directory and rename it to `diffusion_python_model.safetensors`.

Thats what I did. Although not from this exact links. But other links.

However, it seems to be a separate issue. Cause I tried the original catVTON repo & tried to run it via gradio. Got the same error as this one.

The models files in hugginface doesn't exist anymore. Tried logging into hugginface - cli, no dice.

Seems `couldn't connect to hugginface` is an error that comes up in other areas too.

**Comment by kaiyes** [comment]
![image](https://github.com/user-attachments/assets/69a0550c-799b-4b48-bedd-7c039ac19788)
![image](https://github.com/user-attachments/assets/e711e572-ad54-401e-9321-26f82bc145b7)
![image](https://github.com/user-attachments/assets/f497a785-57c3-4900-8f8a-f6d2e3fd8e9b)
