### ISSUE TITLE
出现stable-diffusion-inpainting错误

### ISSUE THREAD

**Issue by leetraman822** [chflame163/ComfyUI_CatVTON_Wrapper#4]
运行到CatVTON Wrapper时出现以下错误
!!! Exception during processing!!! We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like F:\StableDiffusion\ComfyUI_windows\ComfyUI\models\CatVTON\stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 380, in load_config
    config_file = hf_hub_download(
                  ^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'F:\StableDiffusion\ComfyUI_windows\ComfyUI\models\CatVTON\stable-diffusion-inpainting'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\StableDiffusion\ComfyUI_windows\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\cat_vton.py", line 41, in catvton
    pipeline = CatVTONPipeline(
               ^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper\py\catvton\pipeline.py", line 40, in __init__
    self.noise_scheduler = DDIMScheduler.from_pretrained(base_ckpt, subfolder="scheduler")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 143, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
                                  ^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\StableDiffusion\ComfyUI_windows\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like F:\StableDiffusion\ComfyUI_windows\ComfyUI\models\CatVTON\stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

网络可以正常访问HF并快速下载模型，不知道是怎么回事

**Comment by leetraman822** [comment]
啊 好像是我的模型路径放错了。。。😂

**Comment by ClothingAI** [comment]
> 啊 好像是我的模型路径放错了。。。😂

(it seems my model path is misplaced) in case someone reads this.

**Comment by kaiyes** [comment]
Hey I have the same error. Where do we copy these files ? 
![image](https://github.com/user-attachments/assets/b4aedca6-b51a-4bc6-a904-415307107d0f)
![image](https://github.com/user-attachments/assets/35c527e7-b479-4b42-82fd-ec2aa2b16fd2)

**Comment by kaiyes** [comment]
![image](https://github.com/user-attachments/assets/aa9127ce-d9e9-49dc-bbe9-db63242e0b17)

**Comment by leetraman822** [comment]
> Hey I have the same error. Where do we copy these files ? ![image](https://private-user-images.githubusercontent.com/5293742/362623021-b4aedca6-b51a-4bc6-a904-415307107d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Nzg2ODYsIm5iZiI6MTcyNDk3ODM4NiwicGF0aCI6Ii81MjkzNzQyLzM2MjYyMzAyMS1iNGFlZGNhNi1iNTFhLTRiYzYtYTkwNC00MTUzMDcxMDdkMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDAzOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVkOGJlNmQxMWI0MmMxYTQ5MDJkZWQ1YTU3YjVlMDI3MmE0M2QzNzJiMTk3YjFkMjZlMjk4YjA4YzI4MDQ5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0TzdCYXVUZ0KsBHmMeTW79E7BBdnEhE0ohFMteokW2I) ![image](https://private-user-images.githubusercontent.com/5293742/362623276-35c527e7-b479-4b42-82fd-ec2aa2b16fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Nzg2ODYsIm5iZiI6MTcyNDk3ODM4NiwicGF0aCI6Ii81MjkzNzQyLzM2MjYyMzI3Ni0zNWM1MjdlNy1iNDc5LTRiNDItODJmZC1lYzJhYTJiMTZmZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDAzOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU3ZWI3NWVhNjk5OWJmNWJkNzkwMzU1ZTcyMzRlN2Y3MmI0MmQ0MTVhYTNkODUxNTE3OTAxZDY5MjQzNGQxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PkiUHu1az9CtuQCim7WAjba-vig_tqL5D3hPj1-kl9Y)

Hello, This is my folder structure.
![微信截图_20240830084441](https://github.com/user-attachments/assets/a255db67-0af7-4df0-9297-14146888b0c5)
![微信截图_20240830084451](https://github.com/user-attachments/assets/1a8d8f63-50de-48ad-9fe0-7fe6fa84c8f2)

**Comment by kaiyes** [comment]
yeah exactly same as mine. 

I wonder why mine doesn't work.

I'm getting the `can't connect to huggingface` error. 

<img width="558" alt="Screenshot 2024-08-30 at 12 54 43 PM" src="https://github.com/user-attachments/assets/b0adbd55-3d17-4c2d-946e-08f458b89b47">
