### ISSUE TITLE
Uploading upscaled images not working.

### ISSUE THREAD

**Issue by wonchooo** [chflame163/ComfyUI_CatVTON_Wrapper#41]
When I use upscaled images as reference image the result image is just the masked image.
Here is a sample, I want to change the upper clothes and this is the result.

The first image is an upscaled image that I use as reference image

![ComfyUI_temp_apenr_00043_](https://github.com/user-attachments/assets/40b2c4c7-86f0-4593-a69c-29843d64d363)
![ComfyUI_temp_apenr_00108_](https://github.com/user-attachments/assets/5e08a68f-86e3-45dc-9937-ab65eb44d0ac)

**Comment by wonchooo** [comment]
Hi chlame163, just want to let you know you really did an amazing work!

I use CatVTON Wrapper, and SegmentAnythingUltra V2.

**Comment by chflame163** [comment]
I tried running with this image, although the segmentation was not very ideal, at least it roughly made her change clothes.
![微信图片_20241203212418_看图王](https://github.com/user-attachments/assets/00798982-39f8-4b76-a447-33fda8001027)
